### ISSUE TITLE
Separate oko from mujjingun.github.io?

### ISSUE THREAD

**Issue by ayaka14732** [mujjingun/oko#2]
Thanks for this great project!

I believe it would be better that oko is developed in a separate repository, rather than the default repository mujjingun.github.io.

My suggestions:

- Rename the repository mujjingun.github.io to oko
- Rename the file `oko.html` to `index.html` (So that it can be accessed from <https://mujjingun.github.io/oko/>)
- Create a new repository mujjingun.github.io
- Create a file `oko.html` in the new repository to redirect <https://mujjingun.github.io/oko.html> to <https://mujjingun.github.io/oko/>

**Comment by mujjingun** [comment]
Done!
